// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhatTrienNhanSu.DbContexts;

#nullable disable

namespace DBContext.Migrations
{
    [DbContext(typeof(PhatTrienNhanSuDbContext))]
    [Migration("20251029143643_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationHours")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<string>("Keyword")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ProviderID")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.HasIndex("ProviderID");

                    b.ToTable("CourseCatalog");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.EmployeeSurveyResponse", b =>
                {
                    b.Property<int>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseID"));

                    b.Property<int>("CatalogID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelEnhanceKnowledge")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelNecessary")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelUpdateKnowledge")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelVeryNecessary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyPeriodId")
                        .HasColumnType("int");

                    b.HasKey("ResponseID");

                    b.HasIndex("CatalogID");

                    b.HasIndex("SurveyPeriodId");

                    b.HasIndex("EmployeeID", "CatalogID", "SurveyPeriodId")
                        .IsUnique();

                    b.ToTable("EmployeeSurveyResponses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.SurveyPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyword")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SurveyPeriods");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProviderCode")
                        .IsUnique();

                    b.ToTable("TrainingProviders");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", b =>
                {
                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.TrainingProvider", "Provider")
                        .WithMany("CourseCatalogs")
                        .HasForeignKey("ProviderID");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.EmployeeSurveyResponse", b =>
                {
                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", "CourseCatalog")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("CatalogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.SurveyPeriod", "SurveyPeriod")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("SurveyPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseCatalog");

                    b.Navigation("SurveyPeriod");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", b =>
                {
                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.SurveyPeriod", b =>
                {
                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingProvider", b =>
                {
                    b.Navigation("CourseCatalogs");
                });
#pragma warning restore 612, 618
        }
    }
}
