// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhatTrienNhanSu.DbContexts;

#nullable disable

namespace DBContext.Migrations
{
    [DbContext(typeof(PhatTrienNhanSuDbContext))]
    partial class PhatTrienNhanSuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", b =>
                {
                    b.Property<int>("CatalogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatalogID"));

                    b.Property<string>("Area")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DurationHours")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CatalogID");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.ToTable("CourseCatalog");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.EmployeeSurveyResponse", b =>
                {
                    b.Property<int>("ResponseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseID"));

                    b.Property<int>("CatalogID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelEnhanceKnowledge")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelNecessary")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelUpdateKnowledge")
                        .HasColumnType("bit");

                    b.Property<bool>("LevelVeryNecessary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SurveyPeriodId")
                        .HasColumnType("int");

                    b.HasKey("ResponseID");

                    b.HasIndex("CatalogID");

                    b.HasIndex("SurveyPeriodId");

                    b.HasIndex("EmployeeID", "CatalogID", "SurveyPeriodId")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_Employee_Survey_Item");

                    b.ToTable("EmployeeSurveyResponses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.EmployeeTrainingRegistration", b =>
                {
                    b.Property<int>("RegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationID"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<bool>("Certificate")
                        .HasColumnType("bit");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistrationID");

                    b.HasIndex("CourseID");

                    b.HasIndex("ProgramID");

                    b.HasIndex("EmployeeID", "CourseID")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_Employee_Course_Registration");

                    b.ToTable("EmployeeTrainingRegistrations");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.SurveyPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("SurveyPeriods");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingCourse", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(5, 1)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxAttendees")
                        .HasColumnType("int");

                    b.Property<int>("ProgramID")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseID");

                    b.HasIndex("ProgramID");

                    b.ToTable("TrainingCourses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProgramID");

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.EmployeeSurveyResponse", b =>
                {
                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", "CourseCatalog")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("CatalogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.SurveyPeriod", "SurveyPeriod")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("SurveyPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseCatalog");

                    b.Navigation("SurveyPeriod");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.EmployeeTrainingRegistration", b =>
                {
                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.TrainingCourse", "TrainingCourse")
                        .WithMany("Registrations")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.TrainingProgram", "TrainingProgram")
                        .WithMany("Registrations")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TrainingCourse");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingCourse", b =>
                {
                    b.HasOne("PhatTrienNhanSu.DbContexts.Entities.TrainingProgram", "TrainingProgram")
                        .WithMany("TrainingCourses")
                        .HasForeignKey("ProgramID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.CourseCatalog", b =>
                {
                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.SurveyPeriod", b =>
                {
                    b.Navigation("SurveyResponses");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingCourse", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("PhatTrienNhanSu.DbContexts.Entities.TrainingProgram", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("TrainingCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
